id: PYSEC-2020-232
details: In freewvs before 0.1.1, a user could create a large file that freewvs will
  try to read, which will terminate a scan process. This has been patched in 0.1.1.
affected:
- package:
    name: freewvs
    ecosystem: PyPI
    purl: pkg:pypi:freewvs
  ranges:
  - type: GIT
    repo: https://github.com/schokokeksorg/freewvs
    events:
    - introduced: "0"
    - fixed: 18bbf2043e53f69e0119d24f8ae4edb274afb9b2
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 0.1.1
  versions:
  - 0.1.0
references:
- type: FIX
  url: https://github.com/schokokeksorg/freewvs/commit/18bbf2043e53f69e0119d24f8ae4edb274afb9b2
- type: ADVISORY
  url: https://github.com/schokokeksorg/freewvs/security/advisories/GHSA-9cfv-9463-8gqv
aliases:
- CVE-2020-15100
- GHSA-9cfv-9463-8gqv
modified: "2021-08-27T03:22:04.199703Z"
published: "2020-07-14T20:15:00Z"
