affected:
- package:
    ecosystem: PyPI
    name: tensorflow-gpu
    purl: pkg:pypi:tensorflow-gpu
  ranges:
  - events:
    - introduced: '0'
    - fixed: 9294094df6fea79271778eb7e7ae1bad8b5ef98f
    repo: https://github.com/tensorflow/tensorflow
    type: GIT
  - events:
    - introduced: '0'
    - fixed: 2.4.4
    - introduced: 2.5.0
    - fixed: 2.5.2
    - introduced: 2.6.0
    - fixed: 2.6.1
    - introduced: 2.7.0rc0
    - fixed: 2.7.0
    type: ECOSYSTEM
aliases:
- CVE-2021-41198
- GHSA-2p25-55c9-h58q
details: TensorFlow is an open source platform for machine learning. In affected versions
  if `tf.tile` is called with a large input argument then the TensorFlow process will
  crash due to a `CHECK`-failure caused by an overflow. The number of elements in
  the output tensor is too much for the `int64_t` type and the overflow is detected
  via a `CHECK` statement. This aborts the process. The fix will be included in TensorFlow
  2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2,
  and TensorFlow 2.4.4, as these are also affected and still in supported range.
id: PYSEC-0000-CVE-2021-41198
modified: '2021-11-13T06:52:42.007550Z'
published: '2021-11-05T20:15:00Z'
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/9294094df6fea79271778eb7e7ae1bad8b5ef98f
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2p25-55c9-h58q
- type: REPORT
  url: https://github.com/tensorflow/tensorflow/issues/46911
