affected:
- package:
    ecosystem: PyPI
    name: tensorflow-gpu
    purl: pkg:pypi:tensorflow-gpu
  ranges:
  - events:
    - introduced: '0'
    - fixed: 3cbb917b4714766030b28eba9fb41bb97ce9ee02
    repo: https://github.com/tensorflow/tensorflow
    type: GIT
  - events:
    - introduced: '0'
    - fixed: 2.3.1
    type: ECOSYSTEM
aliases:
- CVE-2020-15198
- GHSA-jc87-6vpp-7ff3
details: In Tensorflow before version 2.3.1, the `SparseCountSparseOutput` implementation
  does not validate that the input arguments form a valid sparse tensor. In particular,
  there is no validation that the `indices` tensor has the same shape as the `values`
  one. The values in these tensors are always accessed in parallel. Thus, a shape
  mismatch can result in accesses outside the bounds of heap allocated buffers. The
  issue is patched in commit 3cbb917b4714766030b28eba9fb41bb97ce9ee02 and is released
  in TensorFlow version 2.3.1.
id: PYSEC-0000-CVE-2020-15198
modified: '2021-09-01T08:19:33.154302Z'
published: '2020-09-25T19:15:00Z'
references:
- type: WEB
  url: https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/3cbb917b4714766030b28eba9fb41bb97ce9ee02
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-jc87-6vpp-7ff3
