id: PYSEC-0000-CVE-2021-4118
details: pytorch-lightning is vulnerable to Deserialization of Untrusted Data
affected:
- package:
    name: pytorch-lightning
    ecosystem: PyPI
    purl: pkg:pypi:pytorch-lightning
  ranges:
  - type: GIT
    repo: https://github.com/pytorchlightning/pytorch-lightning
    events:
    - introduced: "0"
    - fixed: 62f1e82e032eb16565e676d39e0db0cac7e34ace
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 1.6.0
references:
- type: FIX
  url: https://github.com/pytorchlightning/pytorch-lightning/commit/62f1e82e032eb16565e676d39e0db0cac7e34ace
- type: WEB
  url: https://huntr.dev/bounties/31832f0c-e5bb-4552-a12c-542f81f111e6
- type: ADVISORY
  url: https://github.com/advisories/GHSA-2vj5-px25-gjrp
aliases:
- CVE-2021-4118
- GHSA-2vj5-px25-gjrp
modified: "2022-01-04T16:27:00Z"
published: "2021-12-23T18:15:00Z"
